# Generated by Django 3.0.2 on 2020-01-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0003_auto_20200110_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приветсвие пользователя'), (1, 'Спрашиваем имя'), (2, 'Спрашиваем о себе'), (3, 'Спрашиваем соц сети'), (4, 'Спрашиваем город'), (5, 'Профиль сохранен'), (6, 'Участвуем в следующей рассылке'), (7, 'Человек подтвердил участие в рассылке'), (8, 'Человек отказался от участия в рассылке')], primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsclub_bot.Location'),
        ),
    ]
