# Generated by Django 3.0.2 on 2020-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0004_auto_20200113_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
    ]
