# Generated by Django 3.0.2 on 2020-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0005_remove_person_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
