# Generated by Django 3.0.2 on 2020-01-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0006_person_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_message_send', models.BooleanField(default=False)),
                ('rate', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('from_invite_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kidsclub_bot.InviteIntent')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kidsclub_bot.Person', to_field='tg_id')),
                ('to_invite_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kidsclub_bot.InviteIntent')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kidsclub_bot.Person', to_field='tg_id')),
            ],
            options={
                'unique_together': {('from_person', 'to_person')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='meetings',
            field=models.ManyToManyField(related_name='person_meeting', through='kidsclub_bot.PersonMeeting', to='kidsclub_bot.Person'),
        ),
    ]
