# Generated by Django 3.0.2 on 2020-01-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0007_auto_20200113_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmeeting',
            name='from_invite_intent',
        ),
        migrations.RemoveField(
            model_name='personmeeting',
            name='to_invite_intent',
        ),
        migrations.AddField(
            model_name='inviteintent',
            name='person_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsclub_bot.PersonMeeting'),
        ),
    ]
