# Generated by Django 3.0.2 on 2020-01-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0008_auto_20200114_0001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personmeeting',
            unique_together=set(),
        ),
    ]
