# Generated by Django 3.0.2 on 2020-01-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0009_auto_20200114_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmessage',
            options={'verbose_name': 'Шаблон сообщения', 'verbose_name_plural': 'Шаблоны сообщений'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='personmeeting',
            options={'verbose_name': 'Встреча пользователя', 'verbose_name_plural': 'Встречи пользователей'},
        ),
        migrations.AddField(
            model_name='person',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приветсвие пользователя'), (1, 'Спрашиваем имя'), (2, 'Спрашиваем о себе'), (3, 'Спрашиваем соц сети'), (4, 'Спрашиваем город'), (5, 'Профиль сохранен'), (6, 'Участвуем в следующей рассылке'), (7, 'Человек подтвердил участие в рассылке'), (8, 'Человек отказался от участия в рассылке'), (9, 'Информация о встрече')], primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='inviteintent',
            name='person_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsclub_bot.PersonMeeting'),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_networks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personmeeting',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personmeeting',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
