# Generated by Django 3.0.2 on 2020-01-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0010_auto_20200114_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmeeting',
            name='is_feedback_message_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приветсвие пользователя'), (1, 'Спрашиваем имя'), (2, 'Спрашиваем о себе'), (3, 'Спрашиваем соц сети'), (4, 'Спрашиваем город'), (5, 'Профиль сохранен'), (6, 'Участвуем в следующей рассылке'), (7, 'Человек подтвердил участие в рассылке'), (8, 'Человек отказался от участия в рассылке'), (9, 'Информация о встрече'), (10, 'Юзернейм не установлен'), (11, 'Фидбек, встреча прошла хорошо'), (12, 'Фидбек, встреча прошла плохо'), (13, 'Фидбек, не встретились'), (14, 'Фидбек, отзыв собран')], primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personmeeting',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(0, 'Хорошо'), (1, 'Плохо'), (2, 'Не встретились')], null=True),
        ),
    ]
