# Generated by Django 3.0.2 on 2020-01-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidsclub_bot', '0011_auto_20200114_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='about',
        ),
        migrations.AddField(
            model_name='person',
            name='kid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приветсвие пользователя'), (2, 'Спрашиваем о себе'), (3, 'Спрашиваем соц сети'), (4, 'Спрашиваем город'), (5, 'Профиль сохранен'), (6, 'Участвуем в следующей рассылке'), (7, 'Человек подтвердил участие в рассылке'), (8, 'Человек отказался от участия в рассылке'), (9, 'Информация о встрече'), (10, 'Юзернейм не установлен'), (11, 'Фидбек, встреча прошла хорошо'), (12, 'Фидбек, встреча прошла плохо'), (13, 'Фидбек, не встретились'), (14, 'Фидбек, отзыв собран'), (15, 'Фидбек, как прошло')], primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PersonKid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Мальчик'), (1, 'Девочка')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsclub_bot.Person')),
            ],
        ),
    ]
