# Generated by Django 3.0.2 on 2020-01-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0002_auto_20190109_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'Инфо о событиях', 'verbose_name_plural': 'Инфо о событиях'},
        ),
    ]
